spring:
  application:
    name: produto-service
  h2:
    console:
      settings:
        trace: true
   
server:
  port: ${PORT:0}
  error:
    whitelabel:
      enabled: false
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
